git_author = "MEGA"
git_email = "admin@mega.org"
workspace = "/home/skiner/megadir6/mount"
store_path = "/home/skiner/megadir6/store"
base_url = "http://localhost:8000"
config_file = "config.toml"
file_blob_endpoint = "http://localhost:8000/api/v1/file/blob"
